"use client"

import jsPDF from 'jspdf'
import html2canvas from 'html2canvas'

export interface UserDataExport {
  userName: string
  email: string
  stats: {
    totalPhotos: number
    totalVideos: number
    totalJournals: number
    lastActive: Date
    streak: number
  }
  recentActivity: Array<{
    id: string
    type: 'photo' | 'video' | 'journal'
    title: string
    createdAt: Date
    thumbnail?: string
  }>
  exportDate: string
}

export const exportUserDataToPDF = async (userData: UserDataExport): Promise<void> => {
  try {
    const pdf = new jsPDF()

    // Title page
    pdf.setFontSize(24)
    pdf.setTextColor(40, 40, 40)
    pdf.text('VidoraFrameForge Data Export', pdf.internal.pageSize.width / 2, 50, { align: 'center' })

    pdf.setFontSize(14)
    pdf.setTextColor(100, 100, 100)
    pdf.text(`Exported on ${new Date(userData.exportDate).toLocaleDateString()}`, pdf.internal.pageSize.width / 2, 70, { align: 'center' })

    // User info
    pdf.setFontSize(16)
    pdf.setTextColor(40, 40, 40)
    pdf.text('User Information', 20, 100)

    pdf.setFontSize(12)
    pdf.setTextColor(60, 60, 60)
    pdf.text(`Name: ${userData.userName}`, 20, 120)
    pdf.text(`Email: ${userData.email}`, 20, 135)
    pdf.text(`Last Active: ${new Date(userData.stats.lastActive).toLocaleDateString()}`, 20, 150)

    // Statistics
    pdf.setFontSize(16)
    pdf.setTextColor(40, 40, 40)
    pdf.text('Statistics', 20, 180)

    pdf.setFontSize(12)
    pdf.setTextColor(60, 60, 60)
    pdf.text(`Total Photos: ${userData.stats.totalPhotos}`, 20, 200)
    pdf.text(`Total Videos: ${userData.stats.totalVideos}`, 20, 215)
    pdf.text(`Total Journals: ${userData.stats.totalJournals}`, 20, 230)
    pdf.text(`Current Streak: ${userData.stats.streak} days`, 20, 245)

    // Recent Activity
    pdf.addPage()
    pdf.setFontSize(16)
    pdf.setTextColor(40, 40, 40)
    pdf.text('Recent Activity', 20, 30)

    pdf.setFontSize(11)
    pdf.setTextColor(60, 60, 60)

    let yPosition = 50
    userData.recentActivity.forEach((activity, index) => {
      if (yPosition > pdf.internal.pageSize.height - 30) {
        pdf.addPage()
        yPosition = 30
      }

      const activityType = activity.type.charAt(0).toUpperCase() + activity.type.slice(1)
      const date = activity.createdAt.toLocaleDateString()
      pdf.text(`${index + 1}. ${activityType}: ${activity.title}`, 20, yPosition)
      pdf.text(`   Date: ${date}`, 20, yPosition + 8)
      yPosition += 20
    })

    // Footer
    const pageCount = pdf.getNumberOfPages()
    for (let i = 1; i <= pageCount; i++) {
      pdf.setPage(i)
      pdf.setFontSize(8)
      pdf.setTextColor(150, 150, 150)
      pdf.text(`Generated by VidoraFrameForge on ${new Date().toLocaleDateString()}`, 20, pdf.internal.pageSize.height - 10)
      pdf.text(`Page ${i} of ${pageCount}`, pdf.internal.pageSize.width - 30, pdf.internal.pageSize.height - 10)
    }

    const fileName = `vidoraframeforge_data_${userData.userName.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_${new Date().toISOString().split('T')[0]}.pdf`
    pdf.save(fileName)

  } catch (error) {
    console.error('Error generating user data PDF:', error)
    throw new Error('Failed to generate user data PDF')
  }
}

export const exportJournalToPDF = async (journalData: JournalExportData): Promise<void> => {
  try {
    // Create a new jsPDF instance
    const pdf = new jsPDF()

    // Set up fonts and colors
    pdf.setFont('helvetica', 'normal')

    // Add title
    pdf.setFontSize(20)
    pdf.setTextColor(40, 40, 40)
    const titleLines = pdf.splitTextToSize(journalData.title, 180)
    pdf.text(titleLines, 15, 25)

    let yPosition = 35 + (titleLines.length * 7)

    // Add metadata
    pdf.setFontSize(12)
    pdf.setTextColor(100, 100, 100)

    const metadata = [
      `Author: ${journalData.author}`,
      `Date: ${new Date(journalData.createdAt).toLocaleDateString()}`,
      ...(journalData.mood ? [`Mood: ${journalData.mood}`] : []),
      ...(journalData.location ? [`Location: ${journalData.location}`] : [])
    ]

    metadata.forEach(line => {
      pdf.text(line, 15, yPosition)
      yPosition += 7
    })

    yPosition += 5

    // Add tags if any
    if (journalData.tags && journalData.tags.length > 0) {
      pdf.setFontSize(11)
      pdf.setTextColor(60, 179, 113)
      const tagsText = `Tags: ${journalData.tags.map(tag => `#${tag}`).join(', ')}`
      const tagLines = pdf.splitTextToSize(tagsText, 180)
      pdf.text(tagLines, 15, yPosition)
      yPosition += (tagLines.length * 6) + 10
    }

    // Add content
    pdf.setFontSize(12)
    pdf.setTextColor(40, 40, 40)

    const contentLines = pdf.splitTextToSize(journalData.content, 180)
    const linesPerPage = Math.floor((pdf.internal.pageSize.height - yPosition - 20) / 6)

    let currentPage = 1
    let currentLine = 0

    while (currentLine < contentLines.length) {
      if (currentLine > 0) {
        pdf.addPage()
        yPosition = 20
        currentPage++
      }

      const endLine = Math.min(currentLine + linesPerPage, contentLines.length)
      const pageLines = contentLines.slice(currentLine, endLine)

      pdf.text(pageLines, 15, yPosition)
      currentLine = endLine
    }

    // Add attachments info if any
    if (journalData.attachments && journalData.attachments.length > 0) {
      pdf.addPage()
      pdf.setFontSize(16)
      pdf.setTextColor(40, 40, 40)
      pdf.text('Attachments', 15, 25)

      pdf.setFontSize(11)
      pdf.setTextColor(100, 100, 100)

      journalData.attachments.forEach((attachment, index) => {
        const yPos = 40 + (index * 15)
        if (yPos > pdf.internal.pageSize.height - 20) {
          pdf.addPage()
        }

        const fileName = attachment.fileName || `Attachment ${index + 1}`
        const fileType = attachment.fileType || 'Unknown'
        pdf.text(`${index + 1}. ${fileName} (${fileType})`, 15, yPos)
        pdf.text(`   URL: ${attachment.url}`, 15, yPos + 7)
      })
    }

    // Add footer with generation info
    const pageCount = pdf.getNumberOfPages()
    for (let i = 1; i <= pageCount; i++) {
      pdf.setPage(i)
      pdf.setFontSize(8)
      pdf.setTextColor(150, 150, 150)
      pdf.text(`Generated by VidoraFrameForge on ${new Date().toLocaleDateString()}`, 15, pdf.internal.pageSize.height - 10)
      pdf.text(`Page ${i} of ${pageCount}`, pdf.internal.pageSize.width - 30, pdf.internal.pageSize.height - 10)
    }

    // Save the PDF
    const fileName = `${journalData.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_journal.pdf`
    pdf.save(fileName)

  } catch (error) {
    console.error('Error generating PDF:', error)
    throw new Error('Failed to generate PDF')
  }
}

export const exportMultipleJournalsToPDF = async (journals: JournalExportData[]): Promise<void> => {
  try {
    const pdf = new jsPDF()

    // Add title page
    pdf.setFontSize(24)
    pdf.setTextColor(40, 40, 40)
    pdf.text('Journal Collection', pdf.internal.pageSize.width / 2, 50, { align: 'center' })

    pdf.setFontSize(14)
    pdf.setTextColor(100, 100, 100)
    pdf.text(`Exported on ${new Date().toLocaleDateString()}`, pdf.internal.pageSize.width / 2, 70, { align: 'center' })
    pdf.text(`${journals.length} journal${journals.length !== 1 ? 's' : ''}`, pdf.internal.pageSize.width / 2, 85, { align: 'center' })

    let currentPage = 1

    // Add each journal
    for (const journal of journals) {
      pdf.addPage()
      currentPage++

      // Journal title
      pdf.setFontSize(18)
      pdf.setTextColor(40, 40, 40)
      const titleLines = pdf.splitTextToSize(journal.title, 180)
      pdf.text(titleLines, 15, 25)

      let yPosition = 35 + (titleLines.length * 7)

      // Metadata
      pdf.setFontSize(11)
      pdf.setTextColor(100, 100, 100)

      const metadata = [
        `Author: ${journal.author}`,
        `Date: ${new Date(journal.createdAt).toLocaleDateString()}`,
        ...(journal.mood ? [`Mood: ${journal.mood}`] : []),
        ...(journal.location ? [`Location: ${journal.location}`] : [])
      ]

      metadata.forEach(line => {
        pdf.text(line, 15, yPosition)
        yPosition += 6
      })

      yPosition += 5

      // Tags
      if (journal.tags && journal.tags.length > 0) {
        pdf.setFontSize(10)
        pdf.setTextColor(60, 179, 113)
        const tagsText = `Tags: ${journal.tags.map(tag => `#${tag}`).join(', ')}`
        const tagLines = pdf.splitTextToSize(tagsText, 180)
        pdf.text(tagLines, 15, yPosition)
        yPosition += (tagLines.length * 5) + 8
      }

      // Content
      pdf.setFontSize(11)
      pdf.setTextColor(40, 40, 40)

      const contentLines = pdf.splitTextToSize(journal.content, 180)
      const linesPerPage = Math.floor((pdf.internal.pageSize.height - yPosition - 20) / 5)

      let currentLine = 0

      while (currentLine < contentLines.length) {
        if (currentLine > 0) {
          pdf.addPage()
          currentPage++
          yPosition = 20
        }

        const endLine = Math.min(currentLine + linesPerPage, contentLines.length)
        const pageLines = contentLines.slice(currentLine, endLine)

        pdf.text(pageLines, 15, yPosition)
        currentLine = endLine
      }
    }

    // Add footer to all pages
    const pageCount = pdf.getNumberOfPages()
    for (let i = 1; i <= pageCount; i++) {
      pdf.setPage(i)
      pdf.setFontSize(8)
      pdf.setTextColor(150, 150, 150)
      pdf.text(`Generated by VidoraFrameForge on ${new Date().toLocaleDateString()}`, 15, pdf.internal.pageSize.height - 10)
      pdf.text(`Page ${i} of ${pageCount}`, pdf.internal.pageSize.width - 30, pdf.internal.pageSize.height - 10)
    }

    const fileName = `journal_collection_${new Date().toISOString().split('T')[0]}.pdf`
    pdf.save(fileName)

  } catch (error) {
    console.error('Error generating PDF collection:', error)
    throw new Error('Failed to generate PDF collection')
  }
}